
const fileInput = document.getElementById("audioFile");
const audioPlayer = document.getElementById("audioPlayer");
const analyzeBtn = document.getElementById("analyzeBtn");
const downloadBtn = document.getElementById("downloadBtn");
const statusEl = document.getElementById("status");
const fileInfo = document.getElementById("fileInfo");
const canvas = document.getElementById("waveform");
const ctx = canvas.getContext("2d");

let audioBuffer = null;
let markerSeconds = [];
let selectedName = "audio";

fileInput.addEventListener("change", async () => {
  const file = fileInput.files?.[0];

  if (!file) return;

  selectedName =
    file.name.replace(/\.[^.]+$/, "")
      .replace(/[^a-z0-9_-]/gi, "_") || "audio";

  fileInfo.textContent =
    `${file.name} · ${(file.size / 1024 / 1024).toFixed(2)} MB`;

  audioPlayer.src = URL.createObjectURL(file);
  audioPlayer.hidden = false;

  analyzeBtn.disabled = true;
  downloadBtn.disabled = true;
  markerSeconds = [];
  audioBuffer = null;

  clearStats();
  statusEl.textContent = "Đang đọc âm thanh…";

  try {
    const bytes = await file.arrayBuffer();
    const AudioCtx =
      window.AudioContext || window.webkitAudioContext;

    const audioContext = new AudioCtx();

    audioBuffer = await audioContext.decodeAudioData(bytes);

    await audioContext.close();

    analyzeBtn.disabled = false;
    statusEl.textContent =
      "Đã sẵn sàng. Nhấn “Phân tích nhịp”.";

    document.getElementById("duration").textContent =
      formatTime(audioBuffer.duration);

    drawWaveform([]);
  } catch (error) {
    statusEl.textContent =
      "Không đọc được file này. Hãy thử MP3 hoặc WAV khác.";
    console.error(error);
  }
});

analyzeBtn.addEventListener("click", () => {
  if (!audioBuffer) return;

  statusEl.textContent = "Đang phân tích…";
  analyzeBtn.disabled = true;

  setTimeout(() => {
    try {
      const result = detectBeats(
        audioBuffer,
        document.getElementById("sensitivity").value
      );

      markerSeconds = result.times;

      document.getElementById("bpm").textContent =
        result.bpm ? Math.round(result.bpm) : "—";

      document.getElementById("markers").textContent =
        markerSeconds.length;

      document.getElementById("beatCount").textContent =
        `${markerSeconds.length} marker`;

      drawWaveform(
        result.envelope,
        markerSeconds,
        audioBuffer.duration
      );

      downloadBtn.disabled = markerSeconds.length === 0;

      statusEl.textContent = markerSeconds.length
        ? "Phân tích xong. Hãy nghe thử và tải XML nếu marker phù hợp."
        : "Không phát hiện được nhịp rõ ràng. Hãy thử tăng độ nhạy.";
    } catch (error) {
      console.error(error);
      statusEl.textContent = "Có lỗi khi phân tích âm thanh.";
    } finally {
      analyzeBtn.disabled = false;
    }
  }, 30);
});

downloadBtn.addEventListener("click", () => {
  const fps = Number(document.getElementById("fps").value);
  const width = Number(document.getElementById("width").value);
  const height = Number(document.getElementById("height").value);

  // Đơn vị thời gian bookmark đang giả định là mili giây.
  // Cần xác minh bằng cách nhập XML vào Alight Motion.
  const bookmarks = markerSeconds
    .map(seconds =>
      `  <bookmark t="${Math.round(seconds * 1000)}" />`
    )
    .join("\n");

  const xml = `<?xml version='1.0' encoding='UTF-8' ?>
<!-- Generated by TA Motion Beat Marker. Verify bookmark time units in Alight Motion. -->
<scene title="${escapeXml(selectedName)}"
 width="${width}"
 height="${height}"
 exportWidth="${width}"
 exportHeight="${height}"
 precompose="dynamicResolution"
 bgcolor="#ff000000"
 totalTime="0"
 fps="${fps}"
 modifiedTime="${Date.now()}"
 amver="106019"
 ffver="106"
 am="com.am.nxkfamx/5.0.161.106019"
 amplatform="android"
 retime="freeze"
 retimeAdaptFPS="false">
${bookmarks}
</scene>`;

  const blob = new Blob(
    [xml],
    { type: "application/xml;charset=utf-8" }
  );

  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");

  link.href = url;
  link.download = `${selectedName}_beat_markers.xml`;
  link.click();

  URL.revokeObjectURL(url);
});

function detectBeats(buffer, sensitivity) {
  const sampleRate = buffer.sampleRate;
  const channel = buffer.getChannelData(0);
  const hop = 512;
  const envelope = [];

  // Tính năng lượng RMS theo từng khung âm thanh.
  for (let start = 0; start < channel.length; start += hop) {
    let sum = 0;
    const end = Math.min(start + hop, channel.length);

    for (let i = start; i < end; i++) {
      sum += channel[i] * channel[i];
    }

    envelope.push(
      Math.sqrt(sum / Math.max(1, end - start))
    );
  }

  // Positive spectral-like energy flux.
  const flux = envelope.map((value, index) =>
    Math.max(0, value - (envelope[index - 1] || 0))
  );

  // Làm mượt dữ liệu để giảm nhiễu.
  const smoothRadius = 5;

  const smooth = flux.map((_, index) => {
    let sum = 0;
    let count = 0;

    for (
      let j = Math.max(0, index - smoothRadius);
      j <= Math.min(flux.length - 1, index + smoothRadius);
      j++
    ) {
      sum += flux[j];
      count++;
    }

    return sum / count;
  });

  const factor =
    sensitivity === "high" ? 1.25 :
    sensitivity === "low" ? 2.5 : 1.8;

  const minGap =
    sensitivity === "high" ? 0.22 :
    sensitivity === "low" ? 0.42 : 0.30;

  const localRadius = 18;
  const times = [];

  // Phát hiện các đỉnh năng lượng.
  for (let i = 2; i < flux.length - 2; i++) {
    let local = 0;
    let count = 0;

    for (
      let j = Math.max(0, i - localRadius);
      j <= Math.min(flux.length - 1, i + localRadius);
      j++
    ) {
      local += smooth[j];
      count++;
    }

    const threshold = (local / count) * factor;

    if (
      flux[i] > threshold &&
      flux[i] >= flux[i - 1] &&
      flux[i] > flux[i + 1]
    ) {
      const time = (i * hop) / sampleRate;

      if (
        !times.length ||
        time - times[times.length - 1] >= minGap
      ) {
        times.push(time);
      }
    }
  }

  // Ước lượng BPM từ khoảng cách giữa các marker.
  const intervals = [];

  for (let i = 1; i < times.length; i++) {
    const interval = times[i] - times[i - 1];

    if (interval >= 0.25 && interval <= 1.5) {
      intervals.push(interval);
    }
  }

  const bpm = intervals.length
    ? 60 / median(intervals)
    : 0;

  return { times, bpm, envelope };
}

function drawWaveform(
  envelope,
  markers = [],
  duration = audioBuffer?.duration || 1
) {
  const dpr = window.devicePixelRatio || 1;
  const width = Math.max(300, canvas.clientWidth);
  const height = 120;

  canvas.width = Math.floor(width * dpr);
  canvas.height = Math.floor(height * dpr);

  ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
  ctx.clearRect(0, 0, width, height);

  if (!envelope.length) {
    ctx.strokeStyle = "#29334b";
    ctx.beginPath();
    ctx.moveTo(0, 60);
    ctx.lineTo(width, 60);
    ctx.stroke();
    return;
  }

  const step = Math.max(
    1,
    Math.floor(envelope.length / width)
  );

  const max = Math.max(...envelope) || 1;

  ctx.strokeStyle = "#51d9d0";
  ctx.lineWidth = 1;
  ctx.beginPath();

  for (let x = 0; x < width; x++) {
    const value =
      envelope[Math.min(envelope.length - 1, x * step)] / max;

    const h = Math.max(2, value * 50);

    ctx.moveTo(x, 60 - h);
    ctx.lineTo(x, 60 + h);
  }

  ctx.stroke();

  ctx.strokeStyle = "#ff668e";
  ctx.lineWidth = 1;

  markers.forEach(time => {
    const x = (time / duration) * width;

    ctx.beginPath();
    ctx.moveTo(x, 5);
    ctx.lineTo(x, 115);
    ctx.stroke();
  });
}

function median(values) {
  const sorted = [...values].sort((a, b) => a - b);
  const middle = Math.floor(sorted.length / 2);

  return sorted.length % 2
    ? sorted[middle]
    : (sorted[middle - 1] + sorted[middle]) / 2;
}

function formatTime(seconds) {
  const minutes = Math.floor(seconds / 60);
  const remainder = Math.floor(seconds % 60);

  return `${minutes}:${String(remainder).padStart(2, "0")}`;
}

function clearStats() {
  document.getElementById("duration").textContent = "—";
  document.getElementById("bpm").textContent = "—";
  document.getElementById("markers").textContent = "0";
  document.getElementById("beatCount").textContent = "0 marker";

  drawWaveform([]);
}

function escapeXml(value) {
  return String(value).replace(/[<>&'"]/g, character => ({
    "<": "&lt;",
    ">": "&gt;",
    "&": "&amp;",
    "'": "&apos;",
    '"': "&quot;"
  })[character]);
}

window.addEventListener("resize", () => {
  if (audioBuffer) {
    drawWaveform(
      [],
      markerSeconds,
      audioBuffer.duration
    );
  }
});
    
